# From https://dev.to/rodrigokamada/creating-and-running-an-angular-application-in-a-docker-container-40mk
# TODO: node version
# TODO: broken?
FROM node:alpine as build

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN npm install -g @angular/cli
RUN npm install
RUN ng build

FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/softserve-project-frontend/browser /usr/share/nginx/html
