# From https://dev.to/rodrigokamada/creating-and-running-an-angular-application-in-a-docker-container-40mk
ARG SYSENV=development
FROM node:20.11.1-alpine3.19 as build

WORKDIR /usr/src/app
COPY . /usr/src/app

RUN npm install -g @angular/cli
RUN npm install
RUN ng build --configuration=$SYSENV

FROM nginx:1.25.4-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/softserve-project-frontend/browser /usr/share/nginx/html
